In [8]:
import numpy as np 
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
a = np.random.rand(5,5)
print(a)

[[0.40650192 0.61878748 0.95066566 0.28112277 0.61941157]
 [0.3677301  0.09881881 0.36057625 0.15651695 0.2057202 ]
 [0.49340219 0.75101171 0.49825189 0.12731205 0.07472316]
 [0.88168246 0.89156601 0.92280805 0.50538618 0.43736687]
 [0.47411473 0.19026277 0.68059062 0.31467728 0.81390057]]


In [27]:
pixels = []
for i in range(5):
   pixels.append(i)
print(pixels)

[0, 1, 2, 3, 4]
